#!/command/with-contenv bash
set -e

# Enable debugging if needed
# set -x

s6-echo "Starting unbound"

NAME="unbound"
DESC="DNS server"
DAEMON="/usr/sbin/unbound"
PIDFILE="/run/unbound.pid"
LOGDIR="/var/log/unbound"
LOGFILE="$LOGDIR/unbound.log"
HELPER="/usr/lib/unbound/package-helper"

# Ensure the Unbound log directory exists
mkdir -p "$LOGDIR"

# Ensure the Unbound log file exists
touch "$LOGFILE"

# Ensure the Unbound binary is executable
if [ ! -x "$DAEMON" ]; then
    s6-echo "The Unbound daemon ($DAEMON) is not executable or missing."
    exit 1
fi

# Load environment-specific options
DAEMON_OPTS="${DAEMON_OPTS:-}" # Default to empty if not set

if [ -f /etc/default/unbound ]; then
    . /etc/default/unbound
fi

# Setup chroot and update the root trust anchor
$HELPER chroot_setup
$HELPER root_trust_anchor_update >> "$LOGFILE" 2>&1

# Start Unbound
s6-echo "Running Unbound with options: $DAEMON_OPTS"
exec $DAEMON -d $DAEMON_OPTS >> "$LOGFILE" 2>&1
