version: "3.8"

services:
  big-bear-btop:
    # Build the Docker image using the Dockerfile in the current directory
    build: .
    # Name the container 'big-bear-btop' for easier identification
    container_name: big-bear-btop
    # Run the container in privileged mode to allow access to system metrics
    privileged: true
    # Mount necessary volumes for accessing system information
    volumes:
      # Mount the host's /proc directory to the container's /proc directory
      - /proc:/proc
      # Mount the host's /sys directory to the container's /sys directory
      - /sys:/sys
      # Mount the host's /dev directory to the container's /dev directory
      - /dev:/dev
      # Mount the host's /etc/localtime file to the container's /etc/localtime file (read-only)
      - /etc/localtime:/etc/localtime:ro
      # Mount a local directory for persisting btop configuration files
      - /path/to/local/btop/config:/root/.config/btop
    # Map port 7681 on the host to port 7681 on the container
    ports:
      - "7681:7681"
