services:
  big-bear-casaos-user-management:
    # Build from local Dockerfile for development
    build:
      context: .
      dockerfile: Dockerfile
    # A custom name for the container, making it easier to identify
    container_name: big-bear-casaos-user-management-dev

    ports:
      # Exposing port 5000 on the host and mapping it to port 5000 in the container
      - "5000:5000"

    volumes:
      # Mounting the cgroup filesystem in read-only mode for system resource monitoring
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # Persisting CasaOS database files to retain data across container restarts
      - /var/lib/casaos/db:/var/lib/casaos/db
      # Mounting systemd's runtime directory for integration with the host system
      - /run/systemd/system:/run/systemd/system
      # Providing access to the D-Bus system bus for communication with host services
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      # Mount the app directory for live code changes
      - ./app:/app

    # Ensures the container restarts automatically unless explicitly stopped
    restart: unless-stopped

    environment:
      # Sets the Flask application entry point
      - FLASK_APP=app.py
      # Configures Flask to run in development mode
      - FLASK_ENV=development
      # Enable Flask debug mode
      - FLASK_DEBUG=1
      # Specifies the admin username for the service
      - ADMIN_USERNAME=casaos
      # Specifies the admin password for the service
      - ADMIN_PASSWORD=casaos

    # Grants the container extended privileges, necessary for some operations
    privileged: true

    cap_add:
      # Adds the SYS_ADMIN capability to the container for advanced administrative actions
      - SYS_ADMIN

    security_opt:
      # Disables the default seccomp security profile to allow unrestricted system calls
      - seccomp:unconfined
      
    # Command to run Flask in development mode with auto-reloading
    command: python -m flask run --host=0.0.0.0 --port=5000 --reload
