name: "Build and release for big-bear-casaos-user-management"

on:
  push:
    branches:
      - main
    paths:
      - "Apps/big-bear-casaos-user-management/**"

jobs:
  create:
    name: "Creates the newest release by version"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout project
        uses: actions/checkout@v2.3.4

      # New step to read the VERSION file and set the version as an output
      - name: Get the version
        id: get_version
        run: echo "big_bear_casaos_user_management_version=$(cat Apps/big-bear-casaos-user-management/VERSION)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: ./Apps/big-bear-casaos-user-management
          file: ./Apps/big-bear-casaos-user-management/Dockerfile
          tags: |
            bigbeartechworld/big-bear-casaos-user-management:latest
            bigbeartechworld/big-bear-casaos-user-management:${{ env.big_bear_casaos_user_management_version }}
